### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by pbartela** [Bartozzz/queue-promise#63]
Right now this library does not work on ie 11 because missing babel plugin" form transform classes".
I can make Pr but I'm not sure if this is something you want to add.

**Comment by pbartela** [comment]
that is sadly not enough. Other problems occured

**Comment by Bartozzz** [comment]
I can have a look and add support for IE11 if this is something you need. Initially, it was intended to work with Node.js, not in browser environments.

**Comment by pbartela** [comment]
It would be great! Should I reopen the issue?

**Comment by pbartela** [comment]
I've updated the title as missing support for classes is not the only one problem. For eg. I've found out that IE 11 can't handle default values in function declarations.

**Comment by Bartozzz** [comment]
This issue is strictly related to transpiling. We can add `"ie": "11"` in [`.babelrc` targets](https://github.com/Bartozzz/queue-promise/blob/development/.babelrc#L7) ([documentation](https://babeljs.io/docs/en/babel-preset-env#targets)) and the code should work just fine. However, there are some issues with that:
- we need to add polyfills for [promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility);
- right now, the bundle size is 2.63 KB, once transpiled for IE11 it is more than 2 times that big (even more if we include polyfills directly in the package);

What we might want to do is create a separate bundle for IE9+ only?

**Comment by pbartela** [comment]
If you would that only for me I think we can leave it as it is. I had to write a queue from scratch because of other bugs I've found (which I can see are now fixed).
