### ISSUE TITLE
Event emitter "end" triggers before the queue is finished

### ISSUE THREAD

**Issue by pmfgomes** [Bartozzz/queue-promise#80]
I'm trying to queue a bunch of files to upload and when the queue is finished I want to stop it, so I can do other stuff with the data. 
On end:
```javascript
queue.on("end", () => {
    if (queue.isEmpty) {
      console.log("Queue isEmpty", queue.isEmpty);
      queue.stop();
    }
  });
```

Result:
```
Starting queue...
 LOG  Queue isEmpty true
 LOG  Queue isEmpty true
 LOG  Queue isEmpty true
 LOG  success: 1 failed: 0
```

Last log is when the upload is concluded. Maybe I'm thinking this in a wrong way...

**Comment by Bartozzz** [comment]
Thanks for reporting. I'll have a look at this today and get back to you. 😄

**Comment by Bartozzz** [comment]
@pmfgomes could you send me a minimal reproduction repository or code sample?

**Comment by pmfgomes** [comment]
Sure, but I'll have to create a sample and I can't right now. Tomorrow I will do it

**Comment by pmfgomes** [comment]
I've done the example. In queue.add() you have two examples, one works the other doesn't.
I'm using this in a react native app, so I did this example using react. 

Another problem that I might have is instead of using fetch, I'm using apollo mutations, I will try to make it more simple on my side and test it again.

https://codesandbox.io/s/condescending-chaplygin-y5cxg

**Comment by Bartozzz** [comment]
Oh, I see. This is because you need to properly return the promise that you want the queue to wait for before proceeding.

**Your first example:**

```js =
queue.add(() => queueFetch(url, index));

// …equivalent to:
// queue.add(() => {
//   return queueFetch(url, index);
// });
```

We are adding to the queue a task which fulfills as soon as the promise returned by `queueFetch` has been completed.

**Your second example:**

```js
queue.add(async () => {
  queueFetch(url, index);
});
```

Here you don't return anything, so basically the task completes as soon as it is executed. A working solution would be:

```js
queue.add(async () => {
  await queueFetch(url, index);
});
```

…however, I believe that the first option is preferable in your case. 😄
